server:
  port: 8085
  ssl:
    enabled: false
    keyStore: classpath:keystore.jks
    trustStore: classpath:truststore.jks
    keyStorePassword: password
    trustStorePassword: password
    keyAlias: stories
    clientAuth: WANT
security:
  require-ssl: false
endpoints:
  restart:
    enabled: false
  shutdown:
    enabled: false
  health:
    sensitive: false
management:
  security:
    enabled: false
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.apache.zookeeper: ERROR
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    stream:
      auto-startup: false
      bindings:
        input:
          contentType: text/plain
graphql:
  servlet:
    mapping: /graphql